name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'chore(release)'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm # Default cache directory for npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run build and tests
        run: npm run build
